### ISSUE TITLE
Login Failed !

### ISSUE THREAD

**Issue by hoai97nam** [b31ngd3v/MyIGBot#3]
I have this issue 
`←[91m[✗] Login Failed!←[0m {"user": true, "authenticated": false, "status": "ok"}`
The first time is OK
but the second one I try and fail. I tried on change proxy but the issue still exists.

**Comment by b31ngd3v** [comment]
The password is wrong, that's why you're getting this. **Check your password and try again**. 

It automatically saves the cookie information to use the past session, so you can also use the previous cookie that was automatically genarated when you ran it for first time, to use it just make sure you're running the script from the same directory you ran before.

**Comment by hoai97nam** [comment]
well, it worked. Thanks for your recommends.
